### ISSUE TITLE
While creating live video using aws amplify, video resource is created as undefined and livestream throws error.

### ISSUE THREAD

**Issue by ragamotiki** [awslabs/amplify-video#280]
**Describe the bug**
While creating live video using aws amplify, video resource is created as undefined and livestream throws error.

**To Reproduce**
Please create a video in eu region using amplify add video

**Expected behavior**
Supposed to create a video resource and share live stream 

**Screenshots**
![image](https://user-images.githubusercontent.com/85981938/122163387-696a4600-ce75-11eb-9870-310d41b8db93.png)
![image](https://user-images.githubusercontent.com/85981938/122163443-7dae4300-ce75-11eb-9503-b5ad59993384.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser vs code
 - Version 10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wizage** [comment]
Update to 3.7.0.

Fixed in #275

**Comment by ragamotiki** [comment]
Hi, I am sorry but update what to 3.7.0. My amplify version is 4.52 and node is 12.18.3
![image](https://user-images.githubusercontent.com/85981938/122171754-5a3cc580-ce80-11eb-9396-b55704611b60.png)
I don't remember installing anything else.

Thanks!

**Comment by wizage** [comment]
```npm i amplify-category-video -g```

You installed this plugin this way :)

**Comment by ragamotiki** [comment]
yes i did

**Comment by wizage** [comment]
After installing 3.7.0

You need to run `amplify delete video` and clear the bad undefined resource.

Then run `amplify add video` and create a new livestream and it should work :)

**Comment by ragamotiki** [comment]
I cannot delete because problem occurs while pushing.. cannot delete something which doesn't exist. The following error is thrown when pushed.

![image](https://user-images.githubusercontent.com/85981938/122508604-82ecc880-d002-11eb-9ece-a929e04bc35c.png)

**Comment by wizage** [comment]
This is fixed. Please make sure you are on 3.8.0

**Comment by ragamotiki** [comment]
I am sorry but not fixed. I updated it to 3.8.0 and the problem still persists.
